target_company = [{'name': 'tesla',
                  'ticker': 'TSLA'},
                  {'name': 'apple',
                  'ticker': 'AAPL'},
                  {'name': 'microsoft',
                  'ticker': 'MSFT'},
                  {'name': 'amazon',
                  'ticker': 'AMZN'},
                  {'name': 'google',
                   'ticker': 'GOOGL'}]